export const INSTANCE_LIST_REQUEST = 'INSTANCE_LIST_REQUEST'
export const INSTANCE_LIST_SUCCESS = 'INSTANCE_LIST_SUCCESS'
export const INSTANCE_LIST_FAIL = 'INSTANCE_LIST_FAIL'

export const CHANGE_INSTANCE_STATUS_REQUEST = 'CHANGE_INSTANCE_STATUS_REQUEST'
export const CHANGE_INSTANCE_STATUS_SUCCESS = 'CHANGE_INSTANCE_STATUS_SUCCESS'
export const CHANGE_INSTANCE_STATUS_FAIL = 'CHANGE_INSTANCE_STATUS_FAIL'
