export const INSTANCE_LIST_REQUEST = 'INSTANCE_LIST_REQUEST'
export const INSTANCE_LIST_SUCCESS = 'INSTANCE_LIST_SUCCESS'
export const INSTANCE_LIST_FAIL = 'INSTANCE_LIST_FAIL'

export const CHANGE_INSTANCE_STATUS_REQUEST = 'CHANGE_INSTANCE_STATUS_REQUEST'
export const CHANGE_INSTANCE_STATUS_SUCCESS = 'CHANGE_INSTANCE_STATUS_SUCCESS'
export const CHANGE_INSTANCE_STATUS_FAIL = 'CHANGE_INSTANCE_STATUS_FAIL'

export const GET_INSTANCE_BY_ID_REQUEST = 'GET_INSTANCE_BY_ID_REQUEST'
export const GET_INSTANCE_BY_ID_SUCCESS = 'GET_INSTANCE_BY_ID_SUCCESS'
export const GET_INSTANCE_BY_ID_FAIL = 'GET_INSTANCE_BY_ID_FAIL'

export const CREATE_NEW_INSTANCE_REQUEST = 'CREATE_NEW_INSTANCE_REQUEST'
export const CREATE_NEW_INSTANCE_SUCCESS = 'CREATE_NEW_INSTANCE_SUCCESS'
export const CREATE_NEW_INSTANCE_FAIL = 'CREATE_NEW_INSTANCE_FAIL'

export const DELETE_INSTANCE_REQUEST = 'DELETE_INSTANCE_REQUEST'
export const DELETE_INSTANCE_SUCCESS = 'DELETE_INSTANCE_SUCCESS'
export const DELETE_INSTANCE_FAIL = 'DELETE_INSTANCE_FAIL'

export const GET_INSTANCES_BY_OWNERID_REQUEST = 'GET_INSTANCES_BY_OWNERID_REQUEST'
export const GET_INSTANCES_BY_OWNERID_SUCCESS = 'GET_INSTANCES_BY_OWNERID_SUCCESS'
export const GET_INSTANCES_BY_OWNERID_FAIL = 'GET_INSTANCES_BY_OWNERID_FAIL'

