export const GET_ALL_NETWORKS_REQUEST = 'GET_ALL_NETWORKS_REQUEST'
export const GET_ALL_NETWORKS_SUCCESS = 'GET_ALL_NETWORKS_SUCCESS'
export const GET_ALL_NETWORKS_FAIL = 'GET_ALL_NETWORKS_FAIL'

export const DELETE_NETWORK_BY_ID_REQUEST = 'DELETE_NETWORK_BY_ID_REQUEST'
export const DELETE_NETWORK_BY_ID_SUCCESS = 'DELETE_NETWORK_BY_ID_SUCCESS'
export const DELETE_NETWORK_BY_ID_FAIL = 'DELETE_NETWORK_BY_ID_FAIL'

export const CHANGE_NETWORK_STATUS_REQUEST = 'CHANGE_NETWORK_STATUS_REQUEST'
export const CHANGE_NETWORK_STATUS_SUCCESS = 'CHANGE_NETWORK_STATUS_SUCCESS'
export const CHANGE_NETWORK_STATUS_FAIL = 'CHANGE_NETWORK_STATUS_FAIL'