export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const GET_USERS_BY_TIER_REQUEST = 'GET_USERS_BY_TIER_REQUEST'
export const GET_USERS_BY_TIER_SUCCESS = 'GET_USERS_BY_TIER_SUCCESS'
export const GET_USERS_BY_TIER_FAIL = 'GET_USERS_BY_TIER_FAIL'

export const CHANGE_USER_STATUS_REQUEST = 'CHANGE_USER_STATUS_REQUEST'
export const CHANGE_USER_STATUS_SUCCESS = 'CHANGE_USER_STATUS_SUCCESS'
export const CHANGE_USER_STATUS_FAIL = 'CHANGE_USER_STATUS_FAIL'

export const DELETE_USER_BY_ID_REQUEST = 'DELETE_USER_BY_ID_REQUEST'
export const DELETE_USER_BY_ID_SUCCESS = 'DELETE_USER_BY_ID_SUCCESS'
export const DELETE_USER_BY_ID_FAIL = 'DELETE_USER_BY_ID_FAIL'
